baseurl = "https://darwinleung.github.io/"
languageCode = "en-us"
title = "DL"
theme = "hyde-hyde"
# pygmentsUseClasses = true
PygmentsCodeFences = true
# PygmentsStyle = "monokai"

[taxonomies]
  tag = "tags"
  category = "categories"

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Darwin"
    title = "title"
    description = "Darwin's personal blog"
    copyright = "Built with Hugo and Hyde-hyde ©2018."
    authorimage = "/img/DL_symbol.jpg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    themeColor = "theme-base-0g" # for hyde theme
    highlightjsstyle = "dark"

## Social Accounts
[params.social]
    github = "darwinleung"
    # instagram = "<username>"
    # xing = "<username>"
    linkedin = "darwinleung"
    # twitter = "<username>"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    email = "darwinlkh@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 300
    url = "/contact/"